//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPBT {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class thongtinketxuat : global::System.Configuration.ApplicationSettingsBase {
        
        private static thongtinketxuat defaultInstance = ((thongtinketxuat)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new thongtinketxuat())));
        
        public static thongtinketxuat Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trường THCS Cát Thịnh")]
        public string tendv {
            get {
                return ((string)(this["tendv"]));
            }
            set {
                this["tendv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tenct {
            get {
                return ((string)(this["tenct"]));
            }
            set {
                this["tenct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Thị Ngọc")]
        public string nlb {
            get {
                return ((string)(this["nlb"]));
            }
            set {
                this["nlb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Phan Ngọc Nam")]
        public string ttdv {
            get {
                return ((string)(this["ttdv"]));
            }
            set {
                this["ttdv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bùi Thị Xuân")]
        public string ptkt {
            get {
                return ((string)(this["ptkt"]));
            }
            set {
                this["ptkt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yên Bái")]
        public string diadanh {
            get {
                return ((string)(this["diadanh"]));
            }
            set {
                this["diadanh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bt")]
        public string bt {
            get {
                return ((string)(this["bt"]));
            }
            set {
                this["bt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2014")]
        public string NTT {
            get {
                return ((string)(this["NTT"]));
            }
            set {
                this["NTT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31/12/2014")]
        public string NTD {
            get {
                return ((string)(this["NTD"]));
            }
            set {
                this["NTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Thị Lan")]
        public string thuquy {
            get {
                return ((string)(this["thuquy"]));
            }
            set {
                this["thuquy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11122251")]
        public string madvqhns {
            get {
                return ((string)(this["madvqhns"]));
            }
            set {
                this["madvqhns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Thị Ngọc")]
        public string thukho {
            get {
                return ((string)(this["thukho"]));
            }
            set {
                this["thukho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string namhoc {
            get {
                return ((string)(this["namhoc"]));
            }
            set {
                this["namhoc"] = value;
            }
        }
    }
}
